name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 5.0.x
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.x
    - name: Clean
      run: dotnet clean ./src/RearTools.sln --configuration Release && dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore src/RearTools.sln
    - name: Build
      run: |  
        dotnet build  src/RearTools.sln   -v q  --no-restore
        dotnet publish src/RearTools/RearTools.csproj -f netcoreapp3.1  -r win-x64 -c Release -v q --no-self-contained  --no-restore -o dist/
    - name: deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: admin.xigooo.com
        username: rear
        password: pf2dxGG$Fb6lKW*b
        local-dir: dist/
        server-dir: /
        port: 8021
